<div style="
    background-color: #7BAFD4;
    border-radius: 18px;
    padding: 22px 26px;
    display: flex;
    align-items: center;
    gap: 24px;
    margin-bottom: 18px;
">
    <img src="../592_avatar_lr.png" alt="GEOG 592"
        style="width:110px;height:110px;border-radius:22px;">
    <div>
        <div style="
            font-family: Impact, 'Arial Black', Arial, sans-serif;
            font-size: 42px;
            font-weight: 900;
            letter-spacing: 2px;
            line-height: 1;
            color: white;
        ">GEOG 592</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 700;
            color: #13294B;
            margin-top: 8px;
        ">GIS Programming</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #13294B;
            margin-top: 6px;
        ">Week 4 Homework: Pandas Intro</div>
    </div>
</div>

## Instructions:

Using the cleaned CSV file from the previous homework, create a Jupyter Notebook that opens and explores the data using pandas.

Use the following methods:

df.head()

df.shape

df.columns

df.dtypes

df.info()

Also use a mask to create a dataframe with less rows.

## Dataframe exploration

In [28]:
import pandas as pd 
print(pd.__version__)

3.0.3

In [29]:
df = pd.read_csv("data/bmf_filtered.csv")
df.head()

,ein,org_name_display,org_addr_full,ntee_code_major_group,ntee_code_definition,geo_match_addr,geo_county,geo_lat,geo_lon
0,01-0477310,Christian Mission Services,"200 COMMONWEALTH CT, CARY, NC 27511-2431",UNDEFINED,UNDEFINED,"200 Commonwealth Ct, Cary, North Carolina, 27511",Wake County,35.767120,-78.784764
1,01-0616952,Christ Our Hope Church,"203 CAPCOM AVE, WAKE FOREST, NC 27587-6514",UNDEFINED,UNDEFINED,"203 Capcom Ave, Wake Forest, North Carolina, 2...",Wake County,35.948982,-78.527158
2,01-0636457,Grace Ministries I,"6717 VERNIE DR, RALEIGH, NC 27603-8549",Housing and Shelter,Homeless Shelters,"6717 Vernie Dr, Raleigh, North Carolina, 27603",Wake County,35.589226,-78.625334
3,01-0649099,Apex Highschool A O I T Support,"1501 LAURA DUNCAN RD, APEX, NC 27502-1539",Education,Parent/Teacher Group,"1501 Laura Duncan Rd, Apex, North Carolina, 27502",Wake County,35.744564,-78.836438
4,01-0667136,Reunite Cultures Fund,"7920 LAGENARIA DR, ANGIER, NC 27501-5503","Arts, Culture and Humanities",Music,"7920 Lagenaria Dr, Angier, North Carolina, 27501",Wake County,35.542224,-78.755255

In [30]:
# This is an attribute of the dataframe object. Methods have ().
print(df.shape)

(6310, 9)

In [31]:
df.columns

Index(['ein', 'org_name_display', 'org_addr_full', 'ntee_code_major_group',
       'ntee_code_definition', 'geo_match_addr', 'geo_county', 'geo_lat',
       'geo_lon'],
      dtype='str')

In [32]:
df.dtypes

ein                          str
org_name_display             str
org_addr_full                str
ntee_code_major_group        str
ntee_code_definition         str
geo_match_addr               str
geo_county                   str
geo_lat                  float64
geo_lon                  float64
dtype: object

In [33]:
# Prints the first and last rows 
df.info

<bound method DataFrame.info of              ein                      org_name_display  \
0     01-0477310            Christian Mission Services
1     01-0616952                Christ Our Hope Church
2     01-0636457                    Grace Ministries I
3     01-0649099       Apex Highschool A O I T Support
4     01-0667136                 Reunite Cultures Fund
...          ...                                   ...
6305  99-5045201  North Carolina Cantonese Association
6306  99-5058846                          Dah Ministry
6307  99-5076527                   Reading With George
6308  99-5108063                            Hockey Joy
6309  99-5139323        Our Journey Camping Experience

                                     org_addr_full  \
0         200 COMMONWEALTH CT, CARY, NC 27511-2431
1       203 CAPCOM AVE, WAKE FOREST, NC 27587-6514
2           6717 VERNIE DR, RALEIGH, NC 27603-8549
3        1501 LAURA DUNCAN RD, APEX, NC 27502-1539
4         7920 LAGENARIA DR, ANGIER, NC 27501-5503
...                                            ...
6305      211 WATERFORD LK DR, CARY, NC 27519-8627
6306       4444 ZEBULON RD, ZEBULON, NC 27597-8196
6307       8445 SECRETO DR, RALEIGH, NC 27606-0031
6308  1608 YATES WHEEL WAY, RALEIGH, NC 27606-9527
6309        6028 RICKER RD, RALEIGH, NC 27610-4281

             ntee_code_major_group  \
0                        UNDEFINED
1                        UNDEFINED
2              Housing and Shelter
3                        Education
4     Arts, Culture and Humanities
...                            ...
6305                     Education
6306              Religion-Related
6307                     Education
6308         Recreation and Sports
6309         Recreation and Sports

                                   ntee_code_definition  \
0                                             UNDEFINED
1                                             UNDEFINED
2                                     Homeless Shelters
3                                  Parent/Teacher Group
4                                                 Music
...                                                 ...
6305                    Alliance/Advocacy Organizations
6306                                       Christianity
6307              Fund Raising and/or Fund Distribution
6308                 Fund Raising and Fund Distribution
6309  Physical Fitness and Community Recreational Fa...

                                         geo_match_addr   geo_county  \
0      200 Commonwealth Ct, Cary, North Carolina, 27511  Wake County
1     203 Capcom Ave, Wake Forest, North Carolina, 2...  Wake County
2        6717 Vernie Dr, Raleigh, North Carolina, 27603  Wake County
3     1501 Laura Duncan Rd, Apex, North Carolina, 27502  Wake County
4      7920 Lagenaria Dr, Angier, North Carolina, 27501  Wake County
...                                                 ...          ...
6305  211 Waterford Lake Dr, Cary, North Carolina, 2...  Wake County
6306    4444 Zebulon Rd, Zebulon, North Carolina, 27597  Wake County
6307    8445 Secreto Dr, Raleigh, North Carolina, 27606  Wake County
6308  1608 Yates Wheel Way, Raleigh, North Carolina,...  Wake County
6309     6028 Ricker Rd, Raleigh, North Carolina, 27610  Wake County

        geo_lat    geo_lon
0     35.767120 -78.784764
1     35.948982 -78.527158
2     35.589226 -78.625334
3     35.744564 -78.836438
4     35.542224 -78.755255
...         ...        ...
6305  35.813591 -78.904449
6306  35.904335 -78.370773
6307  35.738830 -78.741553
6308  35.736472 -78.730774
6309  35.733902 -78.538558

[6310 rows x 9 columns]>

## Creating a mask

In [34]:
mask = df['ntee_code_major_group'] == 'Housing and Shelter'
mask.head()

0    False
1    False
2     True
3    False
4    False
Name: ntee_code_major_group, dtype: bool

In [35]:
if len(df) == len(mask):
    print(f"df and mask are the same length ({len(df)} rows).")
else: 
    print("Not the same length.")

df and mask are the same length (6310 rows).

In [36]:
df_housing = df[mask]
df_housing.head()

,ein,org_name_display,org_addr_full,ntee_code_major_group,ntee_code_definition,geo_match_addr,geo_county,geo_lat,geo_lon
2,01-0636457,Grace Ministries I,"6717 VERNIE DR, RALEIGH, NC 27603-8549",Housing and Shelter,Homeless Shelters,"6717 Vernie Dr, Raleigh, North Carolina, 27603",Wake County,35.589226,-78.625334
90,13-4312776,Alabama Nonprofit Housing,"8801 FAST PARK DR STE 117, RALEIGH, NC 27617-4853",Housing and Shelter,Low-Income & Subsidized Rental Housing,"8801 Fast Park Dr, Ste 117, Raleigh, North Car...",Wake County,35.903133,-78.765336
114,16-1640109,Communtiy Apartments Corporation Of Metrolina 5,"353 E SIX FRKS RD STE 300, RALEIGH, NC 27609-7887",Housing and Shelter,Low-Income & Subsidized Rental Housing,"353 E Six Forks Rd, Ste 300, Raleigh, North Ca...",Wake County,35.820510,-78.626132
151,20-0953592,Blessed Life Housing Authority,"6220 BIG SANDY DR, RALEIGH, NC 27616-5797",Housing and Shelter,Housing Support,"6220 Big Sandy Dr, Raleigh, North Carolina, 27616",Wake County,35.891113,-78.536705
325,20-8715100,Captrust Community Foundation,"4208 SIX FRKS RD STE 1700, RALEIGH, NC 27609-5734",Housing and Shelter,Fund Raising and Fund Distribution,"4208 Six Forks Rd, Ste 1700, Raleigh, North Ca...",Wake County,35.836611,-78.640375

In [37]:
df_housing_alt = df[df['ntee_code_major_group'] == 'Housing and Shelter']

df_housing_alt.head()

,ein,org_name_display,org_addr_full,ntee_code_major_group,ntee_code_definition,geo_match_addr,geo_county,geo_lat,geo_lon
2,01-0636457,Grace Ministries I,"6717 VERNIE DR, RALEIGH, NC 27603-8549",Housing and Shelter,Homeless Shelters,"6717 Vernie Dr, Raleigh, North Carolina, 27603",Wake County,35.589226,-78.625334
90,13-4312776,Alabama Nonprofit Housing,"8801 FAST PARK DR STE 117, RALEIGH, NC 27617-4853",Housing and Shelter,Low-Income & Subsidized Rental Housing,"8801 Fast Park Dr, Ste 117, Raleigh, North Car...",Wake County,35.903133,-78.765336
114,16-1640109,Communtiy Apartments Corporation Of Metrolina 5,"353 E SIX FRKS RD STE 300, RALEIGH, NC 27609-7887",Housing and Shelter,Low-Income & Subsidized Rental Housing,"353 E Six Forks Rd, Ste 300, Raleigh, North Ca...",Wake County,35.820510,-78.626132
151,20-0953592,Blessed Life Housing Authority,"6220 BIG SANDY DR, RALEIGH, NC 27616-5797",Housing and Shelter,Housing Support,"6220 Big Sandy Dr, Raleigh, North Carolina, 27616",Wake County,35.891113,-78.536705
325,20-8715100,Captrust Community Foundation,"4208 SIX FRKS RD STE 1700, RALEIGH, NC 27609-5734",Housing and Shelter,Fund Raising and Fund Distribution,"4208 Six Forks Rd, Ste 1700, Raleigh, North Ca...",Wake County,35.836611,-78.640375