# Pandas summary

In [155]:
import pandas as pd
print(pd.__version__)

3.0.3

In [156]:
# Reading in a csv and inspecting the dataframe. 
# Printing the first 5 rows.
# Must use pd. to access pandas module. 
# After that, the object is from a pandas class, 
# so can just call the method on the object (dataframe in example)
df = pd.read_csv("physical_NC_with_an_error.csv")
df.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20,Column21,Column22
1,2023,NC,North Carolina,Cleveland,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.2,...,21.5,31.5,"101,378","78,793",37045,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5554731480207 35.3336676514711)
2,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,...,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
3,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,...,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)
4,2023,NC,North Carolina,Beaufort,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26,...,21.4,31,"44,481","35,939",37013,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-76.8589373781447 35.4941226525086)

In [157]:
# Printing the last 5 rows. 
df.tail()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
96,2023,NC,North Carolina,Orange,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,18.4,...,14.8,22.2,"150,626","122,940",37135,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.1206058027686 36.0613413706585)
97,2023,NC,North Carolina,Iredell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,20.7,...,16.7,25.5,"199,710","155,704",37097,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.8731910815794 35.8070107330188)
98,2023,NC,North Carolina,Forsyth,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.5,...,20.1,29.2,"392,921","304,926",37067,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.2562678118814 36.1306194708921)
99,2023,NC,North Carolina,Wake,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,17.9,...,14.8,21.2,"1,190,275","919,538",37183,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-78.6503446201168 35.7900594036584)
100,2023,NC,North Carolina,Macon,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.3,...,19.7,29.5,"38,412","31,394",37113,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-83.4217780844555 35.1506263752147)

In [158]:
# Overview of entire dataframe
df.info

<bound method DataFrame.info of         Year StateAbbr       StateDesc LocationName DataSource  \
0    Column1   Column2         Column3      Column4    Column5
1       2023        NC  North Carolina    Cleveland      BRFSS
2       2023        NC  North Carolina        Burke      BRFSS
3       2023        NC  North Carolina     Alamance      BRFSS
4       2023        NC  North Carolina     Beaufort      BRFSS
..       ...       ...             ...          ...        ...
96      2023        NC  North Carolina       Orange      BRFSS
97      2023        NC  North Carolina      Iredell      BRFSS
98      2023        NC  North Carolina      Forsyth      BRFSS
99      2023        NC  North Carolina         Wake      BRFSS
100     2023        NC  North Carolina        Macon      BRFSS

                  Category                                         Measure  \
0                  Column6                                         Column7
1    Health Risk Behaviors  No leisure-time physical activity among adults
2    Health Risk Behaviors  No leisure-time physical activity among adults
3    Health Risk Behaviors  No leisure-time physical activity among adults
4    Health Risk Behaviors  No leisure-time physical activity among adults
..                     ...                                             ...
96   Health Risk Behaviors  No leisure-time physical activity among adults
97   Health Risk Behaviors  No leisure-time physical activity among adults
98   Health Risk Behaviors  No leisure-time physical activity among adults
99   Health Risk Behaviors  No leisure-time physical activity among adults
100  Health Risk Behaviors  No leisure-time physical activity among adults

    Data_Value_Unit          Data_Value_Type Data_Value  ...  \
0           Column8                  Column9   Column10  ...
1                 %  Age-adjusted prevalence       26.2  ...
2                 %  Age-adjusted prevalence       26.7  ...
3                 %  Age-adjusted prevalence       23.7  ...
4                 %  Age-adjusted prevalence         26  ...
..              ...                      ...        ...  ...
96                %  Age-adjusted prevalence       18.4  ...
97                %  Age-adjusted prevalence       20.7  ...
98                %  Age-adjusted prevalence       24.5  ...
99                %  Age-adjusted prevalence       17.9  ...
100               %  Age-adjusted prevalence       24.3  ...

    Low_Confidence_Limit High_Confidence_Limit TotalPopulation TotalPop18plus  \
0               Column13              Column14        Column15       Column16
1                   21.5                  31.5         101,378         78,793
2                   22.2                  31.5          88,338         72,201
3                   19.3                  28.3         179,165        139,859
4                   21.4                    31          44,481         35,939
..                   ...                   ...             ...            ...
96                  14.8                  22.2         150,626        122,940
97                  16.7                  25.5         199,710        155,704
98                  20.1                  29.2         392,921        304,926
99                  14.8                  21.2       1,190,275        919,538
100                 19.7                  29.5          38,412         31,394

    LocationID CategoryID MeasureId DataValueTypeID  Short_Question_Text  \
0     Column17   Column18  Column19        Column20             Column21
1        37045    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
2        37023    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
3        37001    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
4        37013    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
..         ...        ...       ...             ...                  ...
96       37135    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
97       37097    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
98       37067    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
99       37183    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity
100      37113    RISKBEH       LPA       AgeAdjPrv  Physical Inactivity

                                    Geolocation
0                                      Column22
1    POINT (-81.5554731480207 35.3336676514711)
2      POINT (-81.70486114808 35.7494843806822)
3    POINT (-79.3994760246283 36.0436739846115)
4    POINT (-76.8589373781447 35.4941226525086)
..                                          ...
96   POINT (-79.1206058027686 36.0613413706585)
97   POINT (-80.8731910815794 35.8070107330188)
98   POINT (-80.2562678118814 36.1306194708921)
99   POINT (-78.6503446201168 35.7900594036584)
100  POINT (-83.4217780844555 35.1506263752147)

[101 rows x 22 columns]>

In [159]:
# Subsetting a specific column. 
# Returns a pandas series.
df['LocationName']

0        Column4
1      Cleveland
2          Burke
3       Alamance
4       Beaufort
         ...
96        Orange
97       Iredell
98       Forsyth
99          Wake
100        Macon
Name: LocationName, Length: 101, dtype: str

In [160]:
# Selecting multiple columns.
# Use a list of column names.
df[['LocationName', 'Year', 'Category']]

    LocationName     Year               Category
0        Column4  Column1                Column6
1      Cleveland     2023  Health Risk Behaviors
2          Burke     2023  Health Risk Behaviors
3       Alamance     2023  Health Risk Behaviors
4       Beaufort     2023  Health Risk Behaviors
..           ...      ...                    ...
96        Orange     2023  Health Risk Behaviors
97       Iredell     2023  Health Risk Behaviors
98       Forsyth     2023  Health Risk Behaviors
99          Wake     2023  Health Risk Behaviors
100        Macon     2023  Health Risk Behaviors

[101 rows x 3 columns]

In [161]:
# Find the type of objects 
print(type(df))
print(type(df['Year']))
print(type(df))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [162]:
# dtype attribute, for seeing data types for whole data frame.
df.dtypes

Year                          str
StateAbbr                     str
StateDesc                     str
LocationName                  str
DataSource                    str
Category                      str
Measure                       str
Data_Value_Unit               str
Data_Value_Type               str
Data_Value                    str
Data_Value_Footnote_Symbol    str
Data_Value_Footnote           str
Low_Confidence_Limit          str
High_Confidence_Limit         str
TotalPopulation               str
TotalPop18plus                str
LocationID                    str
CategoryID                    str
MeasureId                     str
DataValueTypeID               str
Short_Question_Text           str
Geolocation                   str
dtype: object

In [163]:
# Attribute that holds the column names of the dataframe
df.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource',
       'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation',
       'TotalPop18plus', 'LocationID', 'CategoryID', 'MeasureId',
       'DataValueTypeID', 'Short_Question_Text', 'Geolocation'],
      dtype='str')

In [164]:
# Can use to replace the column names 
parks = pd.DataFrame({"Park":["Oak","Pine","Maple","Cedar"], "Area":[12,25,18,40], "Visitors":[120,250,180,310]})
parks.columns = ["Parks", "Acreage", "People"]
parks.columns

Index(['Parks', 'Acreage', 'People'], dtype='str')

In [165]:
# Selecting rows. 
df.iloc[0:4]

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20,Column21,Column22
1,2023,NC,North Carolina,Cleveland,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.2,...,21.5,31.5,"101,378","78,793",37045,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5554731480207 35.3336676514711)
2,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,...,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
3,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,...,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)

In [166]:
# index is an attribute of the df object 
# The default is a series of number starting from 0

df.index

RangeIndex(start=0, stop=101, step=1)

In [167]:
# Selecting rows and columns with iloc
df[0:4][['LocationName','StateDesc']]

  LocationName       StateDesc
0      Column4         Column3
1    Cleveland  North Carolina
2        Burke  North Carolina
3     Alamance  North Carolina

In [168]:
# Filtering by conditions in rows 
df[df['TotalPopulation']>'150,000']

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20,Column21,Column22
2,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,...,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
3,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,...,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)
4,2023,NC,North Carolina,Beaufort,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26,...,21.4,31,"44,481","35,939",37013,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-76.8589373781447 35.4941226525086)
5,2023,NC,North Carolina,Caldwell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,25.5,...,20.4,30.9,"80,574","64,820",37027,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5466545637271 35.9530956685159)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023,NC,North Carolina,Guilford,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.5,...,19.4,28.2,"549,866","430,053",37081,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.7889017999481 36.079488692501)
96,2023,NC,North Carolina,Orange,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,18.4,...,14.8,22.2,"150,626","122,940",37135,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.1206058027686 36.0613413706585)
97,2023,NC,North Carolina,Iredell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,20.7,...,16.7,25.5,"199,710","155,704",37097,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.8731910815794 35.8070107330188)
98,2023,NC,North Carolina,Forsyth,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.5,...,20.1,29.2,"392,921","304,926",37067,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.2562678118814 36.1306194708921)
100,2023,NC,North Carolina,Macon,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.3,...,19.7,29.5,"38,412","31,394",37113,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-83.4217780844555 35.1506263752147)

In [169]:
# Multiple conditions 
df[
    (df['TotalPopulation']>'150,000') &
    (df['TotalPop18plus'] >'150,000')
]

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20,Column21,Column22
2,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,...,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
4,2023,NC,North Carolina,Beaufort,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26,...,21.4,31,"44,481","35,939",37013,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-76.8589373781447 35.4941226525086)
5,2023,NC,North Carolina,Caldwell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,25.5,...,20.4,30.9,"80,574","64,820",37027,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5466545637271 35.9530956685159)
6,2023,NC,North Carolina,Anson,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,31.7,...,26.7,37,"21,897","17,493",37007,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.1026872705448 34.9736529585894)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2023,NC,North Carolina,Yadkin,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,25.3,...,20.7,30.5,"37,774","30,051",37197,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.6651545675768 36.1601990907039)
94,2023,NC,North Carolina,Guilford,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.5,...,19.4,28.2,"549,866","430,053",37081,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.7889017999481 36.079488692501)
97,2023,NC,North Carolina,Iredell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,20.7,...,16.7,25.5,"199,710","155,704",37097,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.8731910815794 35.8070107330188)
98,2023,NC,North Carolina,Forsyth,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.5,...,20.1,29.2,"392,921","304,926",37067,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.2562678118814 36.1306194708921)
100,2023,NC,North Carolina,Macon,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.3,...,19.7,29.5,"38,412","31,394",37113,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-83.4217780844555 35.1506263752147)

In [170]:
# Calling a function from the pandas package. 
# Coerce replaces errors with NaN
df['TotalPopulation'] = pd.to_numeric(
    df['TotalPopulation'].str.replace(",", "", regex=False), 
    errors='coerce')

In [171]:
# Check for NaNs
# Returns series of boolean values
df['TotalPopulation'].isna().head()

0     True
1    False
2    False
3    False
4    False
Name: TotalPopulation, dtype: bool

In [172]:
# Count number of NaNs
df['TotalPopulation'].isna().sum()

np.int64(1)

In [173]:
# Drop na drops rows
df.dropna(subset='TotalPopulation')

# Fill na replaces the na values with another value 
df.fillna(0)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column13,Column14,0.0,Column16,Column17,Column18,Column19,Column20,Column21,Column22
1,2023,NC,North Carolina,Cleveland,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.2,...,21.5,31.5,101378.0,"78,793",37045,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5554731480207 35.3336676514711)
2,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,...,22.2,31.5,88338.0,"72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
3,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,...,19.3,28.3,179165.0,"139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)
4,2023,NC,North Carolina,Beaufort,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26,...,21.4,31,44481.0,"35,939",37013,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-76.8589373781447 35.4941226525086)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2023,NC,North Carolina,Orange,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,18.4,...,14.8,22.2,150626.0,"122,940",37135,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.1206058027686 36.0613413706585)
97,2023,NC,North Carolina,Iredell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,20.7,...,16.7,25.5,199710.0,"155,704",37097,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.8731910815794 35.8070107330188)
98,2023,NC,North Carolina,Forsyth,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.5,...,20.1,29.2,392921.0,"304,926",37067,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.2562678118814 36.1306194708921)
99,2023,NC,North Carolina,Wake,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,17.9,...,14.8,21.2,1190275.0,"919,538",37183,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-78.6503446201168 35.7900594036584)
100,2023,NC,North Carolina,Macon,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.3,...,19.7,29.5,38412.0,"31,394",37113,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-83.4217780844555 35.1506263752147)

In [174]:
df['LocationName'].unique()

<StringArray>
[    'Column4',   'Cleveland',       'Burke',    'Alamance',    'Beaufort',
    'Caldwell',       'Anson',    'Buncombe',     'Catawba',      'Bladen',
 ...
      'Person',       'Jones',      'Yadkin',    'Guilford', 'Mecklenburg',
      'Orange',     'Iredell',     'Forsyth',        'Wake',       'Macon']
Length: 101, dtype: str

In [175]:
df['LocationName'].nunique

<bound method IndexOpsMixin.nunique of 0        Column4
1      Cleveland
2          Burke
3       Alamance
4       Beaufort
         ...
96        Orange
97       Iredell
98       Forsyth
99          Wake
100        Macon
Name: LocationName, Length: 101, dtype: str>

In [176]:
df['TotalPopulation'].value_counts()

TotalPopulation
101378.0     1
88338.0      1
179165.0     1
44481.0      1
80574.0      1
            ..
150626.0     1
199710.0     1
392921.0     1
1190275.0    1
38412.0      1
Name: count, Length: 100, dtype: int64

In [177]:
df['TotalPopulation'].duplicated().sum()

np.int64(0)

In [178]:
df['TotalPopulation'].mean()

np.float64(108354.91)

In [181]:
df.groupby('LocationName')['TotalPopulation'].sum()

LocationName
Alamance     179165.0
Alexander     36473.0
Alleghany     11342.0
Anson         21897.0
Ashe          27063.0
               ...
Wayne        118686.0
Wilkes        66013.0
Wilson        78970.0
Yadkin        37774.0
Yancey        18938.0
Name: TotalPopulation, Length: 101, dtype: float64

In [ ]:
# to_csv to write to csv.