<div style="
    background-color: #7BAFD4;
    border-radius: 18px;
    padding: 22px 26px;
    display: flex;
    align-items: center;
    gap: 24px;
    margin-bottom: 18px;
">
    <img src="../592_avatar_lr.png" alt="GEOG 592"
        style="width:110px;height:110px;border-radius:22px;">
    <div>
        <div style="
            font-family: Impact, 'Arial Black', Arial, sans-serif;
            font-size: 42px;
            font-weight: 900;
            letter-spacing: 2px;
            line-height: 1;
            color: white;
        ">GEOG 592</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 700;
            color: #13294B;
            margin-top: 8px;
        ">GIS Programming</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #13294B;
            margin-top: 6px;
        ">Week 07 Homework</div>
    </div>
</div>

## Deadlines: 
Monday - select data and write README file \
Wednesday - make three layers \
Friday - spatial and tabular joins

## Assignment:
Explore GeoPandas and create three new spatial layers using geoprocessing techniques. Each new layer must:

- Use two different input layers
- Use a different geoprocessing method
- Build on a different spatial question or on the results of a previous analysis
 

For example, you could create a layer of hospitals that are within a county. You could not then create a second layer of roads that intersect that same county, because the two analyses are too similar. However, you could create buffers around the hospitals selected in the first analysis and then identify roads that intersect those buffers. In this case, the second analysis builds on the results of the first.

You must also create:

One new layer using a table/attribute join. For example, you could join county polygons to a table containing census data. The resulting layer would contain both the county geometries and the census attributes.
 

One analysis using a spatial join that produces a meaningful tabular result. For example, you could spatially join hospitals to counties and then aggregate the results by county to determine the number of hospitals in each county.
 

You may not use hospitals or census data for this assignment. Those are examples only.

Try to make your analyses and maps relate to a topic that interests you. Be creative in your choice of data and spatial questions. AI use is allowed, but you should be able to explain the code and analysis you submit.

Organize all of your work in a Jupyter Notebook under week08/

Your notebook should clearly show your data sources, the methods you used, the resulting layers, and maps of your results. For the spatial analysis section you need to produce a bar graph or some kind of graph that shows the results of your analysis.

By Monday at 1pm you should have selected data for your analysis.

This can be placed in homework/week07/data

Place the link to a readme file that has an explanation about the data contained in the data/ folder, and the original source of the data. 

By Wednesday at 1pm you should already have made the three new layers. 

Provide the link to your JupyterNotebook. 

By Friday at 1pm you must have finished the spatial and tabular joins. 

Provide the link to your JupyterNotebook. The JN needs to include figures and a narrative explaining the question you are answering by applying the geospatial techniques.

In [54]:
import geopandas as gpd
import pandas as pd

## Large scale solar analysis

Utility scale solar farms need to connect to transmission lines in order to deliver energy to users. If a solar farm is not near an existing transmission line, a new tie-in will have to be built, which is expensive. Therefore, I want to see if large scale solar sites in North Carolina are near transmission lines. \
Source: https://www.solarlandlease.com/solar-farm-connect-grid

In [55]:
# Loading in the polygon data as a gpd 
solar_polygons = gpd.read_file("data/large_scale_solar/solar_facility_polygons.geojson", columns=["case_id", "geometry"])

# Loading in the attribute data as a pd
solar_attributes = pd.read_csv("data/large_scale_solar/solar_facility_attributes.csv")

### Attribute join 
Joining the solar facility attribute data to polygon data based on "case_id" column.

In [56]:
solar_polygons.head()

   case_id                                           geometry
0   400011  MULTIPOLYGON (((-144176.097 -530367.463, -1441...
1   407013  MULTIPOLYGON (((1297102.883 473228.339, 129710...
2   404351  MULTIPOLYGON (((486372.846 -54742.838, 486385....
3   404352  MULTIPOLYGON (((1685015.989 476208.804, 168501...
4   404336  MULTIPOLYGON (((476526.316 296695.628, 476530....

In [57]:
solar_attributes.head()

,case_id,multi_poly,eia_id,p_state,p_county,ylat,xlong,p_area,p_img_date,p_dig_conf,...,p_axis,p_azimuth,p_tilt,p_battery,p_cap_ac,p_cap_dc,p_type,p_agrivolt,p_comm,p_zscore
0,400011,single,2953,OK,Canadian,35.4774,-97.6764,50723,20220621,4,...,single-axis,180.0,25.0,NaN,2.5,3.0,greenfield,non-agrivoltaic,community solar,-0.219022
1,407013,single,67406,NY,Erie,43.0168,-78.9779,77051,20250629,4,...,single-axis,180.0,52.0,NaN,4.0,5.5,greenfield,non-agrivoltaic,community solar,-0.048823
2,404351,single,64787,IL,Macoupin,39.4045,-90.0025,56943,20210905,4,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.308881
3,404352,single,64788,NY,Greene,42.3708,-74.0406,40085,20211106,4,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.000703
4,404336,single,64734,IL,Stephenson,42.3804,-89.8412,55382,20220213,4,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.288227

In [58]:
# Attribute join 
# Default is a left join, keeps geometries 
solar_facilities = solar_polygons.merge(solar_attributes, on="case_id")
solar_facilities.head()

,case_id,geometry,multi_poly,eia_id,p_state,p_county,ylat,xlong,p_area,p_img_date,...,p_axis,p_azimuth,p_tilt,p_battery,p_cap_ac,p_cap_dc,p_type,p_agrivolt,p_comm,p_zscore
0,400011,"MULTIPOLYGON (((-144176.097 -530367.463, -1441...",single,2953,OK,Canadian,35.4774,-97.6764,50723,20220621,...,single-axis,180.0,25.0,NaN,2.5,3.0,greenfield,non-agrivoltaic,community solar,-0.219022
1,407013,"MULTIPOLYGON (((1297102.883 473228.339, 129710...",single,67406,NY,Erie,43.0168,-78.9779,77051,20250629,...,single-axis,180.0,52.0,NaN,4.0,5.5,greenfield,non-agrivoltaic,community solar,-0.048823
2,404351,"MULTIPOLYGON (((486372.846 -54742.838, 486385....",single,64787,IL,Macoupin,39.4045,-90.0025,56943,20210905,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.308881
3,404352,"MULTIPOLYGON (((1685015.989 476208.804, 168501...",single,64788,NY,Greene,42.3708,-74.0406,40085,20211106,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.000703
4,404336,"MULTIPOLYGON (((476526.316 296695.628, 476530....",single,64734,IL,Stephenson,42.3804,-89.8412,55382,20220213,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.288227

In [59]:
solar_facilities.columns

Index(['case_id', 'geometry', 'multi_poly', 'eia_id', 'p_state', 'p_county',
       'ylat', 'xlong', 'p_area', 'p_img_date', 'p_dig_conf', 'p_name',
       'p_year', 'p_pwr_reg', 'p_tech_pri', 'p_tech_sec', 'p_sys_type',
       'p_axis', 'p_azimuth', 'p_tilt', 'p_battery', 'p_cap_ac', 'p_cap_dc',
       'p_type', 'p_agrivolt', 'p_comm', 'p_zscore'],
      dtype='str')

### Changing the projection

In [60]:
solar_facilities.crs

<Projected CRS: ESRI:102008>
Name: North_America_Albers_Equal_Area_Conic
Axis Info [cartesian]:
- [east]: Easting (metre)
- [north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Albers Equal Area
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [61]:
solar_facilities = solar_facilities.to_crs(epsg=6543)
solar_facilities.head()

,case_id,geometry,multi_poly,eia_id,p_state,p_county,ylat,xlong,p_area,p_img_date,...,p_axis,p_azimuth,p_tilt,p_battery,p_cap_ac,p_cap_dc,p_type,p_agrivolt,p_comm,p_zscore
0,400011,"MULTIPOLYGON (((-3527564.676 1150549.469, -352...",single,2953,OK,Canadian,35.4774,-97.6764,50723,20220621,...,single-axis,180.0,25.0,NaN,2.5,3.0,greenfield,non-agrivoltaic,community solar,-0.219022
1,407013,"MULTIPOLYGON (((2005540.745 3383919.222, 20055...",single,67406,NY,Erie,43.0168,-78.9779,77051,20250629,...,single-axis,180.0,52.0,NaN,4.0,5.5,greenfield,non-agrivoltaic,community solar,-0.048823
2,404351,"MULTIPOLYGON (((-1109953.986 2232538.025, -111...",single,64787,IL,Macoupin,39.4045,-90.0025,56943,20210905,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.308881
3,404352,"MULTIPOLYGON (((3350120.914 3180326.017, 33501...",single,64788,NY,Greene,42.3708,-74.0406,40085,20211106,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.000703
4,404336,"MULTIPOLYGON (((-946084.299 3310828.383, -9461...",single,64734,IL,Stephenson,42.3804,-89.8412,55382,20220213,...,single-axis,25.0,NaN,NaN,2.0,3.0,greenfield,non-agrivoltaic,community solar,-0.288227

### Filtering data 
Filtering for just NC. Also filtering out community solar, since these projects are smaller and use lines with lower voltage than transmission lines.

In [62]:
# Filtering for just NC
solar_facilities = solar_facilities[solar_facilities["p_state"] == "NC"]
solar_facilities.head()

,case_id,geometry,multi_poly,eia_id,p_state,p_county,ylat,xlong,p_area,p_img_date,...,p_axis,p_azimuth,p_tilt,p_battery,p_cap_ac,p_cap_dc,p_type,p_agrivolt,p_comm,p_zscore
263,407366,"MULTIPOLYGON (((1616249.939 727070.92, 1616251...",multi,68601,NC,Davidson,35.7420,-80.2924,290262,20251009,...,single-axis,180.0,0.0,NaN,4.5,5.0,greenfield,non-agrivoltaic,NaN,-0.802075
311,406473,"MULTIPOLYGON (((2356426.466 1012027.551, 23564...",multi,67161,NC,Northampton,36.5361,-77.7661,1681058,20240528,...,fixed-tilt,180.0,15.0,NaN,120.0,201.0,greenfield,non-agrivoltaic,NaN,0.621402
314,400471,"MULTIPOLYGON (((1335595.878 653578.348, 133544...",multi,58332,NC,Lincoln,35.5260,-81.2351,85746,20210408,...,fixed-tilt,180.0,20.0,NaN,5.0,6.0,greenfield,non-agrivoltaic,NaN,-0.068396
315,400725,"MULTIPOLYGON (((2338720.503 617243.755, 233872...",multi,58782,NC,Wayne,35.4388,-77.8636,94069,20220917,...,fixed-tilt,180.0,20.0,NaN,5.0,7.0,greenfield,non-agrivoltaic,NaN,-0.006649
321,400464,"MULTIPOLYGON (((1354431.33 745049.187, 1354432...",multi,58315,NC,Catawba,35.7785,-81.1767,109744,20210825,...,fixed-tilt,180.0,25.0,NaN,5.0,6.5,greenfield,non-agrivoltaic,NaN,-0.217854

In [ ]:
# Checking to see the term used for community solar
solar_facilities["p_comm"].unique()

<StringArray>
[nan]
Length: 1, dtype: str

There aren't any community solar facilities in NC, so the dataframe doesn't need to be filtered after all.

In [65]:
# Changing the name to solar_farms because I keep misspelling facilities and making a copy for good measure. 
solar_farms = solar_facilities.copy()

### Buffering the polygons

### Clipping the transmission line data

In [ ]:
# Loading in the transmission line data as a gpd
transmission_lines = gpd.read_file("data/large_scale_solar/transmission_lines.geojson")

# Loading in the North Carolina state outline polygon

In [ ]:
# Clipping the transmission line data to the NC polygon

### Intersecting the polygons and the transmission lines

### Analysis
Counting the number of transmission lines that intersect with the buffered polygons and creating a Boolean column for those that do not have a transmission line intersection